### PR TITLE
Adjustment/handle rotating mirrors

### PR DESCRIPTION
**Pull request by BenWeiTang**
Trello card: https://trello.com/c/wJRAl5zM

### CODE REVIEW

**Comment by FishError** [comment]
Right now it looks like the amount it rotates before waiting is a static 360 degrees. Could you instead add an inspector variable so the rotation amount isn't static.

**Comment by BenWeiTang** [comment]
@FishError 
Should it be like a denominator that specifies how a full revolution should be divided into? For example, if I say 5, everytime it rotates, it only does so for 72 degrees because 360 / 5 = 72. 

Or should it be like number of degrees that it rotates every time in between stops?

**Comment by FishError** [comment]
I think it should be a number of degrees that it rotates every time before it stops. This way we aren't restricted with a 360 limit and its also simpler.

**Comment by BenWeiTang** [comment]
@FishError not too sure how to notify you about the new commits I just made since the pr wasn't previously closed that I could open again. But can you take a look at the changes?

**Comment by FishError** [comment]
I think you get email updates whenever a commit or a comment is made if you are a reviewer for a PR. You can also just ping the reviewers in discord whenever you are ready for a review.

**Review by FishError — APPROVED** [review]

**Review by xcrowy — APPROVED** [review]

**Pull request merged**
