### PR TITLE
Updated movement tutorial

### PR DESCRIPTION
**Pull request by Jabgithub23**
No colliders on graybox objs they are just holders until the art team is done. Lmk if I missed anything but this general layout will be it with slight alteration to the gap portion depending on feedback as to how it could look better

### CODE REVIEW

**Review by Nick-77ab2 — CHANGES_REQUESTED** [review]
Currently pressing play on the level loads into demo level 2. make sure to fix that.

**Review by KaifengZhou — CHANGES_REQUESTED** [review]
The objects being placed all have no colliders, and thus the player can walk through them. 
The player can just walk around the gap in the floor.
The objects should be closer together or introduce a invisible wall to stop the players from going past the boundary.
The player reset is not set up correctly, so when the player falls, they don't respawn.
Also we should put a message before the gap telling the player to jump.

**Comment by KaifengZhou** [comment]
For the resetting you can either contact Jacky or me about how that would work, Jacky was the one that came up with the system, but I have some experience using it.

**Comment by Jabgithub23** [comment]
After abt 4 Unity crashes they are in a state of about 98% readiness. The last few issues involving the light switch for opening a door, rotating a door/wall, and having void objects not show in the mirror are all that are left I believe. Want to go over those in the next meeting to get quickly fixed and then implement finished art assets.

**Pull request closed without merging**
